# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from concurrent.futures import ThreadPoolExecutor

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setMinimumSize(550, 500)
        Form.setMaximumSize(600, 700)
        Form.setStyleSheet("background-color: rgb(197, 197, 197);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.display = QtWidgets.QLineEdit(Form)
        self.display.setMinimumSize(QtCore.QSize(350, 100))
        self.display.setStyleSheet("background-color: rgb(127, 127, 127);\n"
"border-radius: 5px;font: 87 28pt 'Segoe UI Black';\n")
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ac = QtWidgets.QPushButton(Form)
        self.ac.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ac.setFont(font)
        self.ac.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n background-color: rgb(46, 168, 169);"
"")
        self.ac.setObjectName("ac")
        self.horizontalLayout.addWidget(self.ac)
        self.backspace = QtWidgets.QPushButton(Form)
        self.backspace.setMinimumSize(QtCore.QSize(50, 50))
        self.backspace.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n background-color: rgb(46, 168, 169);  "
"")
        self.backspace.setObjectName("backspace")
        self.horizontalLayout.addWidget(self.backspace)
        self.percentage = QtWidgets.QPushButton(Form)
        self.percentage.setMinimumSize(QtCore.QSize(50, 50))
        self.percentage.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.percentage.setObjectName("percentage")
        self.horizontalLayout.addWidget(self.percentage)
        self.divide = QtWidgets.QPushButton(Form)
        self.divide.setMinimumSize(QtCore.QSize(50, 50))
        self.divide.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.divide.setObjectName("divide")
        self.horizontalLayout.addWidget(self.divide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.seven = QtWidgets.QPushButton(Form)
        self.seven.setMinimumSize(QtCore.QSize(50, 50))
        self.seven.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.seven.setObjectName("seven")
        self.horizontalLayout_2.addWidget(self.seven)
        self.eight = QtWidgets.QPushButton(Form)
        self.eight.setMinimumSize(QtCore.QSize(50, 50))
        self.eight.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.eight.setObjectName("eight")
        self.horizontalLayout_2.addWidget(self.eight)
        self.nine = QtWidgets.QPushButton(Form)
        self.nine.setMinimumSize(QtCore.QSize(50, 50))
        self.nine.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.nine.setObjectName("nine")
        self.horizontalLayout_2.addWidget(self.nine)
        self.multiply = QtWidgets.QPushButton(Form)
        self.multiply.setMinimumSize(QtCore.QSize(50, 50))
        self.multiply.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.multiply.setObjectName("multiply")
        self.horizontalLayout_2.addWidget(self.multiply)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.four = QtWidgets.QPushButton(Form)
        self.four.setMinimumSize(QtCore.QSize(50, 50))
        self.four.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.four.setObjectName("four")
        self.horizontalLayout_3.addWidget(self.four)
        self.five = QtWidgets.QPushButton(Form)
        self.five.setMinimumSize(QtCore.QSize(50, 50))
        self.five.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.five.setObjectName("five")
        self.horizontalLayout_3.addWidget(self.five)
        self.six = QtWidgets.QPushButton(Form)
        self.six.setMinimumSize(QtCore.QSize(50, 50))
        self.six.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.six.setObjectName("six")
        self.horizontalLayout_3.addWidget(self.six)
        self.subtract = QtWidgets.QPushButton(Form)
        self.subtract.setMinimumSize(QtCore.QSize(50, 50))
        self.subtract.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.subtract.setObjectName("subtract")
        self.horizontalLayout_3.addWidget(self.subtract)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.one = QtWidgets.QPushButton(Form)
        self.one.setMinimumSize(QtCore.QSize(50, 50))
        self.one.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.one.setObjectName("one")
        self.horizontalLayout_4.addWidget(self.one)
        self.two = QtWidgets.QPushButton(Form)
        self.two.setMinimumSize(QtCore.QSize(50, 50))
        self.two.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.two.setObjectName("two")
        self.horizontalLayout_4.addWidget(self.two)
        self.three = QtWidgets.QPushButton(Form)
        self.three.setMinimumSize(QtCore.QSize(50, 50))
        self.three.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.three.setObjectName("three")
        self.horizontalLayout_4.addWidget(self.three)
        self.add = QtWidgets.QPushButton(Form)
        self.add.setMinimumSize(QtCore.QSize(50, 50))
        self.add.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.add.setObjectName("add")
        self.horizontalLayout_4.addWidget(self.add)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.double_zero = QtWidgets.QPushButton(Form)
        self.double_zero.setMinimumSize(QtCore.QSize(50, 50))
        self.double_zero.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.double_zero.setObjectName("double_zero")
        self.horizontalLayout_5.addWidget(self.double_zero)
        self.zero = QtWidgets.QPushButton(Form)
        self.zero.setMinimumSize(QtCore.QSize(50, 50))
        self.zero.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.zero.setObjectName("zero")
        self.horizontalLayout_5.addWidget(self.zero)
        self.decimal = QtWidgets.QPushButton(Form)
        self.decimal.setMinimumSize(QtCore.QSize(50, 50))
        self.decimal.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.decimal.setObjectName("decimal")
        self.horizontalLayout_5.addWidget(self.decimal)
        self.equal = QtWidgets.QPushButton(Form)
        self.equal.setMinimumSize(QtCore.QSize(50, 50))
        self.equal.setStyleSheet("font: 87 28pt \"Segoe UI Black\";\n"
"")
        self.equal.setObjectName("equal")
        self.horizontalLayout_5.addWidget(self.equal)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # ADDED BY ME STARTS
        self.operand_1  = ""
        self.operand_2 = ""
        self.number = ""
        self.one.clicked.connect(self.one_fn)
        self.two.clicked.connect(self.two_fn)
        self.three.clicked.connect(self.three_fn)
        self.four.clicked.connect(self.four_fn)
        self.five.clicked.connect(self.five_fn)
        self.six.clicked.connect(self.six_fn)
        self.seven.clicked.connect(self.seven_fn)
        self.eight.clicked.connect(self.eight_fn)
        self.nine.clicked.connect(self.nine_fn)
        self.zero.clicked.connect(self.zero_fn)
        self.double_zero.clicked.connect(self.double_zero_fn)
        self.decimal.clicked.connect(self.decimal_fn)
        self.ac.clicked.connect(self.clear)
        self.backspace.clicked.connect(self.back_space)
        self.add.clicked.connect(self.add_fn)
        self.subtract.clicked.connect(self.subtract_fn)
        self.multiply.clicked.connect(self.multiply_fn)
        self.divide.clicked.connect(self.divide_fn)
        self.equal.clicked.connect(self.equal_fn)
        self.percentage.clicked.connect(self.percent_fn)



    def one_fn(self):
        self.number += "1"
        self.display_number()
    def two_fn(self):
        self.number += "2"
        self.display_number()

    def three_fn(self):
        self.number += "3"
        self.display_number()

    def four_fn(self):
        self.number += "4"
        self.display_number()

    def five_fn(self):
        self.number += "5"
        self.display_number()

    def six_fn(self):
        self.number += "6"
        self.display_number()

    def seven_fn(self):
        self.number += "7"
        self.display_number()

    def eight_fn(self):
        self.number += "8"
        self.display_number()

    def nine_fn(self):
        self.number += "9"
        self.display_number()

    def zero_fn(self):
        self.number += "0"
        self.display_number()

    def double_zero_fn(self):
        self.number += "00"
        self.display_number()

    def decimal_fn(self):
        self.number += "."
        self.display_number()

    def clear(self):
        self.display.setText("")
        self.number = ""


    def display_number(self):
        self.display.setText(self.number)

    def back_space(self):
        self.number = self.number[:-1]
        self.display_number()

    def add_fn(self):
        self.number += "+"
        self.display_number()

    def subtract_fn(self):
        self.number += "-"
        self.display_number()

    def multiply_fn(self):
        self.number += "*"
        self.display_number()

    def divide_fn(self):
        self.number += "/"
        self.display_number()

    def percent_fn(self):
        self.number += "%"
        self.display_number()

    def percent_expression(self, expression):
        if "%" in expression:
            expression_item = expression.replace("+", " ").replace("-", " ").replace("*", " ").replace("/", " ").split()
            if len(expression_item) == 1:
                num, p = expression_item[0].split("%")
                result = (float(num) / 100)
                expression = expression.replace(expression_item[0], str(result))
                return expression
            else:
                for i in expression_item:
                    if "%" in i:
                        indx = expression_item.index(i)
                        num, p = expression_item[indx].split("%")
                        x = float(expression_item[indx - 1])
                        result = (x * (float(num) / 100))
                        expression = expression.replace(i, str(result))
                        return expression
        else:
            return expression

    def equal_fn(self):
        try:
            number = self.percent_expression(self.number)
            result = str(eval(number))
        except Exception as E:
            self.display.setText("Invalid Expression")
        else:
            self.display.setText(result)
            self.number = result

    # ADDED BY ME ENDS


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CALCULATOR"))
        Form.setWindowIcon(QtGui.QIcon("calculator.png"))
        self.ac.setText(_translate("Form", "AC"))
        self.backspace.setText(_translate("Form", "«"))
        self.percentage.setText(_translate("Form", "%"))
        self.divide.setText(_translate("Form", "÷"))
        self.seven.setText(_translate("Form", "7"))
        self.eight.setText(_translate("Form", "8"))
        self.nine.setText(_translate("Form", "9"))
        self.multiply.setText(_translate("Form", "x"))
        self.four.setText(_translate("Form", "4"))
        self.five.setText(_translate("Form", "5"))
        self.six.setText(_translate("Form", "6"))
        self.subtract.setText(_translate("Form", "-"))
        self.one.setText(_translate("Form", "1"))
        self.two.setText(_translate("Form", "2"))
        self.three.setText(_translate("Form", "3"))
        self.add.setText(_translate("Form", "+"))
        self.double_zero.setText(_translate("Form", "00"))
        self.zero.setText(_translate("Form", "0"))
        self.decimal.setText(_translate("Form", "."))
        self.equal.setText(_translate("Form", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
