# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todolist.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
import datetime
from logics.taskmanager import ManageTask
from data.category import Task, Project, Custom
import json


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 750)
        Form.setStyleSheet("background-color: rgb(255, 246, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 170))
        self.widget_2.setStyleSheet("background-color: rgb(255, 252, 253);\n"
"border-radius:10px;")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.task_name_in = QtWidgets.QLineEdit(self.widget_2)
        self.task_name_in.setMinimumSize(QtCore.QSize(0, 50))
        self.task_name_in.setStyleSheet("background-color:rgb(205, 205, 205, 50);\n"
"font: 10pt \"Arial\";\n"
"border-radius:10px;\n"
"")
        self.task_name_in.setObjectName("task_name_in")
        self.verticalLayout_6.addWidget(self.task_name_in)
        self.category_in = QtWidgets.QLineEdit(self.widget_2)
        self.category_in.setMinimumSize(QtCore.QSize(0, 50))
        self.category_in.setStyleSheet("background-color:rgb(205, 205, 205, 50);\n"
"font: 10pt \"Arial\";\n"
"border-radius:10px;\n"
"")
        self.category_in.setObjectName("category_in")
        self.verticalLayout_6.addWidget(self.category_in)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setMinimumSize(QtCore.QSize(30, 50))
        self.label_7.setStyleSheet("\n"
"font: 75 10pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.due_date_in = QtWidgets.QDateEdit(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.due_date_in.setFont(font)
        self.due_date_in.setObjectName("due_date_in")
        self.horizontalLayout_4.addWidget(self.due_date_in)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.mark_finished_in = QtWidgets.QCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mark_finished_in.setFont(font)
        self.mark_finished_in.setMinimumSize(QtCore.QSize(30, 50))
        self.mark_finished_in.setStyleSheet("font: 75 10pt \"Arial\";")
        self.mark_finished_in.setObjectName("mark_finished_in")
        self.horizontalLayout_6.addWidget(self.mark_finished_in)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_bt = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_bt.setFont(font)
        self.add_bt.setMinimumSize(QtCore.QSize(30, 50))
        self.add_bt.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"border-radius:10px;\n"
"color:white;")
        self.add_bt.setObjectName("add_bt")
        self.horizontalLayout_3.addWidget(self.add_bt)
        self.remove_bt = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.remove_bt.setFont(font)
        self.remove_bt.setMinimumSize(QtCore.QSize(30, 50))
        self.remove_bt.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"border-radius:10px;\n"
"color:white;")
        self.remove_bt.setObjectName("remove_bt")
        self.horizontalLayout_3.addWidget(self.remove_bt)
        self.update_bt = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.update_bt.setFont(font)
        self.update_bt.setMinimumSize(QtCore.QSize(30, 50))
        self.update_bt.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"border-radius:10px;\n"
"color:white;")
        self.update_bt.setObjectName("update_bt")
        self.horizontalLayout_3.addWidget(self.update_bt)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.save_in = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_in.setFont(font)
        self.save_in.setMinimumSize(QtCore.QSize(30, 50))
        self.save_in.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"border-radius:10px;\n"
"color:white;")
        self.save_in.setObjectName("save_in")
        self.horizontalLayout_5.addWidget(self.save_in)
        self.clear_all_in = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_all_in.setFont(font)
        self.clear_all_in.setMinimumSize(QtCore.QSize(30, 50))
        self.clear_all_in.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"border-radius:10px;\n"
"color:white;")
        self.clear_all_in.setObjectName("clear_all_in")
        self.horizontalLayout_5.addWidget(self.clear_all_in)
        self.close_in = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.close_in.setFont(font)
        self.close_in.setMinimumSize(QtCore.QSize(30, 50))
        self.close_in.setStyleSheet("background-color: rgb(250, 0, 0);\n"
"border-radius:10px;\n"
"color:white;")
        self.close_in.setObjectName("close_in")
        self.horizontalLayout_5.addWidget(self.close_in)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(200, 170))
        self.widget.setStyleSheet("background-color: rgb(255, 252, 253);\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.taskname = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.taskname.setFont(font)
        self.taskname.setText("")
        self.taskname.setObjectName("taskname")
        self.verticalLayout_4.addWidget(self.taskname)
        self.category = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.category.setFont(font)
        self.category.setText("")
        self.category.setObjectName("category")
        self.verticalLayout_4.addWidget(self.category)
        self.addedon = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addedon.setFont(font)
        self.addedon.setText("")
        self.addedon.setObjectName("addedon")
        self.verticalLayout_4.addWidget(self.addedon)
        self.duedate = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.duedate.setFont(font)
        self.duedate.setText("")
        self.duedate.setObjectName("duedate")
        self.verticalLayout_4.addWidget(self.duedate)
        self.status = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.verticalLayout_4.addWidget(self.status)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 226, 179);\n"
"border-radius:10px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setMinimumSize(QtCore.QSize(300, 320))
        self.listWidget.setStyleSheet("background-color: rgb(253, 255, 205);\n"
"border-radius:10px\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    # custom part
        self.due_date_in.setDate(QDate(datetime.datetime.now().date()))
        self.task_manager = ManageTask()
        self.data = self.task_manager.data
        self.entry_date = self.get_added_date()
        self.init_list()
        self.add_bt.clicked.connect(self.add_task)
        self.remove_bt.clicked.connect(self.remove_task)
        self.update_bt.clicked.connect(self.update_task)
        self.listWidget.clicked.connect(self.get_info)
        self.clear_all_in.clicked.connect(self.clear_all)
        self.close_in.clicked.connect(self.close)

    # custom function
    def get_added_date(self):
        date = datetime.datetime.now().date()
        y, m, d = str(date).split("-")
        return f"{d}-{m}-{y}"


    def add_task(self):
        item = self.task_name_in.text()
        due_date = self.due_date_in.text()
        category = self.category_in.text().lower()
        added_on = self.get_added_date()
        if item != "":
            if category == "task":
                self.task_manager.add_todo(Task(item, added_on, due_date))
            elif category == "project":
                self.task_manager.add_todo(Project(item, added_on, due_date))
            else:
                self.task_manager.add_todo(Custom(item, added_on, due_date))
            self.due_date_in.setDate(QDate(datetime.datetime.now().date()))
            self.listWidget.addItem(item)
            self.category_in.setText("")
            self.task_name_in.setText("")
        else:
            pass

    def remove_task(self):
        index = self.listWidget.currentRow()
        item = self.listWidget.currentItem()
        if item is not None:
            self.listWidget.takeItem(index)
            self.task_manager.rm_todo(Task(item.text()))
        else:
            pass

    def update_task(self):
        item = self.listWidget.currentItem()
        if item is not None:
            due_date = self.due_date_in.text()
            mark_finished = self.mark_finished_in.isChecked()
            self.task_manager.update(Task(item.text()), due_date, mark_finished)


    def init_list(self):
        try:
            for item in self.data.get("todos").keys():
                self.listWidget.addItem(item)
        except Exception as E:
            print(E)

    def get_info(self):
        current = self.listWidget.currentRow()
        item = self.listWidget.currentItem().text()
        data = self.data.get("todos").get(item)
        d, m, y = list(map(int, self.data.get("todos").get(data.get("task")).get("due_date").split("-")))
        if data is not None:
            self.taskname.setText(data.get("task"))
            self.category.setText(data.get("category_name"))
            self.addedon.setText(data.get("added_on"))
            self.duedate.setText(data.get("due_date"))
            self.due_date_in.setDate(QDate(y, m, d))
            if data.get("is_completed"):
                self.status.setText("Completed")
            else:
                self.status.setText("Pending")
        else:
            pass

    def close(self):
        sys.exit(app.exec_())

    def clear_all(self):
        self.task_manager.clear()
        self.listWidget.clear()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.task_name_in.setPlaceholderText(_translate("Form", "Task Name"))
        self.category_in.setPlaceholderText(_translate("Form", "Category"))
        self.label_7.setText(_translate("Form", "Due Date"))
        self.mark_finished_in.setText(_translate("Form", "Mark finished"))
        self.add_bt.setText(_translate("Form", "Add todo"))
        self.remove_bt.setText(_translate("Form", "Remove todo"))
        self.update_bt.setText(_translate("Form", "update todo"))
        self.save_in.setText(_translate("Form", "Save"))
        self.clear_all_in.setText(_translate("Form", "Clear all"))
        self.close_in.setText(_translate("Form", "Close"))
        self.label_2.setText(_translate("Form", "Task Name"))
        self.label_3.setText(_translate("Form", "Category"))
        self.label_5.setText(_translate("Form", "Added on"))
        self.label_4.setText(_translate("Form", "Due date"))
        self.label_6.setText(_translate("Form", "Status"))
        self.label.setText(_translate("Form", "                            To do list"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    Form.setMinimumSize(1200, 750)
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())